language: ruby
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='50river@travis-ci'
    - GIT_COMMITTER_EMAIL='mr.50river@gmail.com'
    - GIT_AUTHOR_NAME='50river@travis-ci'
    - GIT_AUTHOR_EMAIL='mr.50river@gmail.com'
    - secure: "D/mT2Q4R8UxrQEPi5roc4KoyzR9UbznZQDlPHqur/UlRsG2N4AUjwzTmyuHoaG30/BjEfXiDbQx1/HQvazmGut8e5ZYXrlYJ5okzwVIvNXqJgM/5p08m02t67Mve30UKDKZE1JXJxlLzBDHIDDAlaqQnn4HGqG/lAplc3ifHs90="
before_script:
  - git clone --quiet https://github.com/50river/5374site.git build
  - pushd build
  - git checkout -b gh-pages
  - popd

after_success:
  - cd build
  - git add -A
  - git commit -m 'updated'
  - git push -f --quiet https://$GH_TOKEN@github.com/50river/5374site.git gh-pages
