language: ruby
rvm: 2.0.0
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='cfk-tech@travis-ci'
    - GIT_COMMITTER_EMAIL='cfk-tech@codeforkanazawa.org'
    - GIT_AUTHOR_NAME='cfk-tech@travis-ci'
    - GIT_AUTHOR_EMAIL='cfk-tech@codeforkanazawa.org'
    - secure: "aByGON+4VCcb+UGvjpuTQ9OHQMSXcZ9KYdb3dhzvcP+NVG/EiHp+C9Kb6/k/hlyg2LTBxVzIIkI7qreUY1HiVWnrWOHVzZ+0JaD/p+sDnxPHu8x1mr1ti/Rx4vsHkXCW+55ZbmkGlsBYXu6QD9f2UULRhvPgpgcc/T3j/YJFIzg="
before_script:
  - git clone --quiet https://github.com/codeforkanazawa-org/5374site.git build
  - pushd build
  - git checkout -b gh-pages
  - popd

after_success:
  - cd build
  - git add -A
  - git commit -m 'updated'
  - git push -f --quiet https://$GH_TOKEN@github.com/codeforkanazawa-org/5374site.git gh-pages
